apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "api.fullname" . }}-config
  labels:
    app: {{ include "api.name" . }}
  namespace: {{ .Values.namespace.api.name }}
data:
  SERVER_ADDRESS: {{ .Values.api.server.address | quote }}
  SERVER_PORT: {{ .Values.api.server.port | quote }}
  SPRING_PROFILES_ACTIVE: {{ .Values.api.server.profilesActive | quote }}
  SPRING_MAIL_AUTH_ENABLED: {{ .Values.api.spring.mail.auth.enabled | quote }}
  SPRING_MAIL_TLS_ENABLED: {{ .Values.api.spring.mail.tls.enabled | quote }}
  OTEL_GRPC_ENDPOINT: {{ .Values.api.otel.grpcEndpoint | quote }}
